### ISSUE TITLE
Implement API endpoints to manage ASN descriptions database

### ISSUE THREAD

**Issue by coolparadox** [turbobytes/pulse#14]
Implement http endpoints for managing the ASN descriptions overrides in CNC.

The capability we'd like to have is some sort of:

- `GET /api/asndb/` - Get all contents of the ASN description overrides collection
- `GET /api/asndb/:ASN` - ASN descriptions provided by all available sources.
- `PUT /api/asndb/:ASN` - Store an ASN description override with _id: ASN and description provided in body.

**Comment by coolparadox** [comment]
For completeness, an endpoint for removing an ASN override from the collection would be required as well.

**Comment by coolparadox** [comment]
I have to make an implementation decision here about the approach CNC uses to manage ASN description overrides.

- One approach is to make CNC directly manage the mongodb collection (the same it gave as parameter to geoipdb.NewHandler): list collection, get / set / remove items by accessing mongo. This works because geoipdb.LookupAsn() is aware of any changes to the overrides collection.
- Another approach is to export funcionality to manage ASN overrides by geoipdb itself. There is some of it already implemented -- OverridesSet(), OverridesRemove(). Here CNC would call geoipdb API to manage the collection, no direct access to mongo for this task.

At first glance I like the geoipdb approach better because it would abstract knowledge of a database for managing the collection, so I'd go for it for now. In practice however I see CNC uses mongo a lot already, so this benefit is probably a minor one.

**Comment by coolparadox** [comment]
This issue depends on [geoipdb#16](/turbobytes/geoipdb/issues/16)

**Comment by sajal** [comment]
I am leaning towards doing it in geoipdb because once we start caching, geoipdb would be cache aware and know which cache keys to invalidate based on arguments to `OverridesSet()` `OverridesRemove()`. If we instead do it in CNC, we would need to call some some function in geoipdb to do the invalidation.

**Comment by sajal** [comment]
`DELETE /api/asndb/:ASN` - Remove the override for `ASN`.

**Comment by coolparadox** [comment]
+1

**Comment by coolparadox** [comment]
`GET /asndb/` output sample:

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 72
Content-Type: application/json; charset=UTF-8
Date: Thu, 24 Nov 2016 14:38:46 GMT

[
    {
        "asn": "AS123456",
        "name": "Override value"
    }
]
```

**Comment by coolparadox** [comment]
At the moment, branch _asndb_api_  implements a REST-like API under endpoint `/asndb/` in CNC server for managing the ASN overrides collection:

- `GET /asndb/` - get the full list of ASN description overrides
- `GET /asndb/:ASN` - get the description override for a given ASN
- `PUT /asndb/:ASN` - store a description override for a given ASN
- `DELETE /asndb/:ASN` - delete a description override of a given ASN

As for http status codes, `/asndb/` endpoint does the "expected thing" for several situations: 404 Not Found on GET unknown ASN, 400 Bad Request on malformed PUT etc.

What's missing:

- Return ASN descriptions provided by all available sources through `GET /asndb/:ASN`

I want to suggest detaching this missing feature and have it implemented under another endpoint, say, `/asnlookup/`. Some reasoning towards this suggestion:

1. `/asndb/` would remain solely the management endpoint for our override collection. This is a single well defined scope. Moreover all calls would remain local (no external access) and therefore return quickly.
1. `/asnlookup/` would concentrate ASN lookup capabilities. This is another well defined scope with diverse characteristics than /asndb/, in particular accessing external resources.
1. We may want extend ASN lookup methods (eg. by IP address). We may want to extend its return values in the future.
1. `/asnlookup/` would benefit from [geoipdb caching](/turbobytes/geoipdb/issues/14) when it's implemented, and `/asndb/` won't. The caching can provide a way to do a reverse lookup and find an IP from a ASN, so queries to databases that accept by IP queries only (maxmind, ipinfo) could be performed.

My initial suggestion for `/asnlookup/` endpoint:

- `GET /asnlookup/asn/:ASN` - perform lookups by ASN to all available sources. Make use of cache reverse lookup to try finding an IP from ASN, so by-IP queries to databases can be performed.
- `GET /asnlookup/ip/:IP` - perform lookups by IP to all available sources. Make use of found ASN to query by-ASN databases (eg. cymru).

The above would start concurrent queries to external databases and answer a compound of the results. If there is benefit to it, we may later extend the endpoint to perform specific lookups, eg. `GET /asnlookup/asn/:ASN/geoipdb`, `GET /asnlookup/ip/:IP/maxmind` etc. You get the idea.

**Comment by sajal** [comment]
`/asnlookup/` endpoint approach sounds good to me.
