### ISSUE TITLE
Translate Golang errors to friendly messages in test results

### ISSUE THREAD

**Issue by coolparadox** [turbobytes/pulse#36]
When a Pulse test results in an error, currently the (system) error message is printed as is to the API and UI. This makes it cumbersome for Pulse users with no network experience to understand what happened.

This is a request to show more friendly error messages in Pulse test results.

**Comment by coolparadox** [comment]
I changed ``TranslateError()`` interface to:

```
func TranslateError(result *CombinedResult)
```

There is no return value. On calling, it will (try to) update field ``result.Result.ErrEnglish`` with a friendly error description, if any.

**Comment by coolparadox** [comment]
ab5016d implements my original idea of "regexp and replacement" table for Curl tests. In this implementation, new translations are added to [curlErrorTranslations](https://github.com/turbobytes/pulse/blob/ab5016d03be548749135e9ca98ba030cd7dcf8a7/utils/translate_error.go#L61) as a pair of a matching regexp for the whole Golang error and a replacement text containing a friendly translation.

The replacement text can reference submatches of the matched regexp (eg. ``$1``), as well as predefined named parameters of the test result (eg. ``$DialTimeout``, ``$TcpTime`` etc.).

**Comment by coolparadox** [comment]
This scheme may require more refinements though, as it may not cover all translation cases: as there is only one translation option for each match, there is no room for showing optional timings in translated messages.

For example, on connection timeout error it would be nice to show DNS lookup and TCP connection timings, **if they are available**. This results in variations of translated errors that can't be covered by a simple regexp-and-replacement scheme.

An idea is to develop dedicated translation functions to be called on such cases. Callers would provide the test result structure and regex submatches, and the dedicated function would combine them for mounting variations of the translation.

**Comment by coolparadox** [comment]
[curlErrorTranslations](https://github.com/turbobytes/pulse/blob/f574026d3f94e88fa5c977aa5d31b61527bcb299/utils/translate_error.go#L66) is populated with translations for all agreed HTTP error messages at the moment. Timings in [test cases](https://github.com/turbobytes/pulse/blob/f574026d3f94e88fa5c977aa5d31b61527bcb299/utils/translate_error_test.go#L43) are hand crafted -- it would be nice to use real test data to validate timings shown in unit tests.

**Comment by coolparadox** [comment]
A particular case where distinct translations occur for the same Go error message is TCP Dial timeouts. As a Dial timeout occurs if the sum of DNS lookup and TCP connect durations exceed the threshold, the same system error message, say "``dial tcp some.site.com:80: i/o timeout``", can produce 3 possible outcomes:

- If DNS lookup time is zero (ie, Dial timeout is due to TCP stage alone):
 ``Connection timed out. Could not connect to some.site.com:80 within 15 seconds.``
- If TCP connection time is zero (ie, Dial timeout is due to DNS stage alone):
``DNS lookup timed out. Could not resolve some.site.com within 15 seconds.``
- Otherwise (Dial timeout is due to DNS + TCP stages):
``Lookup with connection timed out. Could not perform DNS lookup and TCP connection to some.site.com within 15 seconds. (DNS lookup 1002ms, TCP connect 14002ms)``

**Comment by coolparadox** [comment]
@sajal: 26f3abc places the error translation job to minions instead of backend as I originally intended. I'd like your feedback about it.

I was facing addressability issues updating ``ErrEnglish`` from inside [Tracker.Runner](https://github.com/turbobytes/pulse/blob/26f3abcc747b0b7a40a894566dc9c2b6c20135fb/cnc.go#L419). As I discovered, ``reply.Result`` does not contain a pointer, and changing any of its fields yields a build error such as ``cannot assign to reply.Result.(pulse.CurlResult).ErrEnglish``.

**Comment by sajal** [comment]
+1 for doing it in minion.
